name: SupeRSoniC-MIUI
on:
  workflow_dispatch:

env:
   CHATID: ${{ secrets.ID_CHANNEL }}
   API_BOT: ${{ secrets.BOT_TOKEN }}
   TYPE_KERNEL: ${{ secrets.NOVIK }}
         
jobs:
   build:
    runs-on: ubuntu-latest

    steps:
    - name: Setting Configurasi
      uses: actions/checkout@v3

    - name: Setup Initialize Environment
      run: |
           chmod +x initialize
           bash initialize
    - name: Starting For Building Your Kernel...
      run: |
           git clone --depth=1 https://github.com/Novik-XIV/SupeRSoniC-Sweet-Kernel -b Backup
           cp sonic-compiler.sh SupeRSoniC-Sweet-Kernel && cd SupeRSoniC-Sweet-Kernel
           chmod +x sonic-compiler.sh && bash sonic-compiler.sh
